# Beer and Bars
1. [Threes Brewing](http://www.threesbrewing.com/): Google told me about this.
2. [Torst](http://www.torstnyc.com/): Beer Bar in Brookly
3. [Blind Tiger](http://www.blindtigeralehouse.com/): Original Beer Bar.  I really want to go here.
4. [Brooklyn Brewery](http://brooklynbrewery.com/): Why not?
5. [Old Town Bar](http://www.oldtownbar.com/): An Old NYC bar
6. [Radegast Hall and Biergarten](http://www.radegasthall.com/): Beer, Sausage, Brookly.  Day drinking?!
7. [The Cannibal](http://www.cannibalnyc.com/): Beer and Butcher
8. [Redd's](http://www.yelp.com/biz/redds-brooklyn): Darts in Williamsburg
9. [Jimmys No. 43](http://jimmysno43.com/): German/Belgian selection.  In East village.

# Sites
1. [The High Line](http://www.thehighline.org/)
2. [Brooklyn Bridge/Brooklyn Bridge Park](http://www.brooklynbridgepark.org/)
3. [Coney Island](http://coneyislandfunguide.com/)
4. [Bldg 92](http://bldg92.org/): Brooklyn Navy Yard Museum

# Food
1. [Katz's](http://katzsdelicatessen.com/): Pastrami!
2. [Brooklyn Farmacy](http://www.brooklynfarmacyandsodafountain.com/): Egg Cream
3. [Nussbaum and Wu](http://www.yelp.com/biz/nussbaum-and-wu-bagel-bakery-cafe-new-york): Black and White Cookie
4. [Williamsburg Pizza](http://slice.seriouseats.com/archives/2012/11/williamsburg-pizza-a-cause-for-celebration.html): NYC Pizza right next to place
5. [Lombardi's](http://www.firstpizza.com/): I still dream of this...
6. [Tasty Hand Pulled Noddles](http://www.tastyhandpullednoodlesnyc.com/): Chinees Noodles
7. [Barney Greengrass](http://barneygreengrass.com/): Bagels and Lox
8. [Momofuku Noodle Bar](https://noodlebar-ny.momofuku.com/): Celebrity Chefs... Why not.
9. [Pier A Harbor House](http://www.piera.com/): My office mate's brothers favorite spot.
10. [Cho Dong Gol](http://www.cdgnyc.com/): Korean
11. [Soba Nippon](http://www.restaurantnippon.com/):Soba!